// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52Fstf-6iCVpd-CuA8gT0q66n2OAGknM',
    appId: '1:392242492343:web:efc3c0c97393434cb2ee32',
    messagingSenderId: '392242492343',
    projectId: 'sistema-integral-2f2c5',
    authDomain: 'sistema-integral-2f2c5.firebaseapp.com',
    storageBucket: 'sistema-integral-2f2c5.firebasestorage.app',
    measurementId: 'G-5T8LRESVLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3m1e3Ta_YVCZH0TVtXnpvX0jK9G5tWdM',
    appId: '1:392242492343:android:bddcd1129a51a209b2ee32',
    messagingSenderId: '392242492343',
    projectId: 'sistema-integral-2f2c5',
    storageBucket: 'sistema-integral-2f2c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxzkkh0jfQgFaBivEYDG4mBY1yrikfuVc',
    appId: '1:392242492343:ios:e0febff23dab9b81b2ee32',
    messagingSenderId: '392242492343',
    projectId: 'sistema-integral-2f2c5',
    storageBucket: 'sistema-integral-2f2c5.firebasestorage.app',
    iosClientId: '392242492343-sg51qqpp27hlvgevs6hcsjq4t30oprq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaIntegral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxzkkh0jfQgFaBivEYDG4mBY1yrikfuVc',
    appId: '1:392242492343:ios:e0febff23dab9b81b2ee32',
    messagingSenderId: '392242492343',
    projectId: 'sistema-integral-2f2c5',
    storageBucket: 'sistema-integral-2f2c5.firebasestorage.app',
    iosClientId: '392242492343-sg51qqpp27hlvgevs6hcsjq4t30oprq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaIntegral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB52Fstf-6iCVpd-CuA8gT0q66n2OAGknM',
    appId: '1:392242492343:web:e1cbb24a4ee076b4b2ee32',
    messagingSenderId: '392242492343',
    projectId: 'sistema-integral-2f2c5',
    authDomain: 'sistema-integral-2f2c5.firebaseapp.com',
    storageBucket: 'sistema-integral-2f2c5.firebasestorage.app',
    measurementId: 'G-BLSQP1G3EK',
  );
}
